import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

import { Toaster } from "~/components/ui/sonner";
import { TRPCReactProvider } from "~/trpc/client";

const font = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${font.className}`}>
        <TRPCReactProvider>
          <NuqsAdapter>
            {children}
            <Toaster richColors theme="light" />
          </NuqsAdapter>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
